### ISSUE TITLE
numbers alignment problem 

### ISSUE THREAD

**Issue by florix91** [MarcinusX/NumberPicker#40] opened 2019-06-05 01:38 UTC
The replicate the problem do this: 
slide the picker to search for a number, but click on it while is rolling and it will stop wherever it is at that moment and misalign the number. I think that after that click it should automatically go and align to the nearest number.

**Comment by MarcinusX** [comment] 2019-08-02 10:20
Duplicate of #38

**Closed by MarcinusX** 2019-08-02 10:20 UTC
Labels: bug, duplicate
