### ISSUE TITLE
The value returned by "onChanged" isn't correct when I scroll to initial value.

### ISSUE THREAD

**Issue by JacksonHiew** [MarcinusX/NumberPicker#92] opened 2021-02-19 06:33 UTC
```dart
NumberPicker.integer(
    initialValue: 1,
    minValue: 1,
    maxValue: 10,
    onChanged: (val) {
        // val will never be "1" even I scrolled to "1", it will return 2.
        // also tested with initialValue: 2, when scroll to 2, it return 3.
    },
);

```

Version: ^1.3.0

==========================

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H15 darwin-x64, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.53.2)
[✓] Connected device (2 available)

• No issues found!

**Comment by Kundan-Android** [comment] 2021-02-19 12:49
same issue I am also facing.

**Comment by MarcinusX** [comment] 2021-04-13 05:54
Hey, this was caused by misleading naming of the `initialValue` which should be the `value` that was needed to be updated. Please see the example. I'm closing this issue. Feel free to reopen if the problem still occurs.

**Closed by MarcinusX** 2021-04-13 05:54 UTC
